apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-accounts-config
  labels:
    app: accounts
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  SERVER_PORT: {{ .Values.service.containerPort | quote }}
  BANK_SECURITY_ENABLED: {{ .Values.security.enabled | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.global.kafka.bootstrapServers }}
  SPRING_CONFIG_ADDITIONAL_LOCATION: /app/config/
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ .Values.global.keycloak.issuerUri }}
              jwk-set-uri: {{ .Values.global.keycloak.jwkSetUri }}
      kafka:
        producer:
          acks: all
          retries: 3
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          properties:
            enable.idempotence: true
            spring.json.add.type.headers: false
    bank:
      kafka:
        topic:
          notifications: bank.notifications
