apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-accounts-config
  labels:
    app: accounts
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  SERVER_PORT: {{ .Values.service.port | quote }}
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.global.keycloak.issuerUri | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: {{ .Values.global.keycloak.jwkSetUri | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI: {{ .Values.global.keycloak.tokenUri | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ACCOUNTS_SERVICE_PROVIDER: keycloak
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ACCOUNTS_SERVICE_AUTHORIZATION_GRANT_TYPE: client_credentials
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ACCOUNTS_SERVICE_CLIENT_ID: {{ .Values.security.oauth2.clientId | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ACCOUNTS_SERVICE_SCOPE: openid
  BANK_SECURITY_ENABLED: {{ .Values.security.enabled | quote }}
