apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-accounts-secret
  labels:
    app: accounts
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.user | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
