apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-credentials
  labels:
    app: keycloak
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  KEYCLOAK_ADMIN: {{ .Values.admin.username | b64enc | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.admin.password | b64enc | quote }}
  KC_DB_USERNAME: {{ .Values.database.user | b64enc | quote }}
  KC_DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
