spring:
  application:
    name: transfer

server:
  port: ${SERVER_PORT:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info
resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 10s

