apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-gateway-config
  labels:
    app: gateway
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  SERVER_PORT: {{ .Values.service.port | quote }}
  BANK_SECURITY_ENABLED: {{ .Values.security.enabled | quote }}
  SPRING_CONFIG_ADDITIONAL_LOCATION: /app/config/
  application.yml: |
    spring:
      application:
        name: gateway
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ .Values.global.keycloak.issuerUri }}
              jwk-set-uri: {{ .Values.global.keycloak.jwkSetUri }}
      cloud:
        gateway:
          default-filters:
            - TokenRelay
          routes:
            - id: accounts
              uri: "http://{{ .Values.global.services.accounts.host }}:{{ .Values.global.services.accounts.port }}"
              predicates:
                - "Path=/api/accounts/**"
            - id: cash
              uri: "http://{{ .Values.global.services.cash.host }}:{{ .Values.global.services.cash.port }}"
              predicates:
                - "Path=/api/cash/**"
            - id: transfer
              uri: "http://{{ .Values.global.services.transfer.host }}:{{ .Values.global.services.transfer.port }}"
              predicates:
                - "Path=/api/transfers/**"
    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus,metrics
      metrics:
        tags:
          application: gateway
      tracing:
        sampling:
          probability: 1.0
      zipkin:
        tracing:
          endpoint: http://{{ .Values.global.zipkin.host }}:{{ .Values.global.zipkin.port }}/api/v2/spans
