replicaCount: 1

image:
  repository: postgres
  tag: "16"
  pullPolicy: IfNotPresent

databases:
  bank:
    name: bank
    user: bank
    password: bank
  keycloak:
    name: keycloak
    user: keycloak
    password: keycloak

service:
  port: 5432

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
