spring:
  application:
    name: gateway

  cloud:
    gateway:
      default-filters:
        - TokenRelay

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info
