apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
    - port: {{ .Values.kibana.service.port }}
      targetPort: {{ .Values.kibana.service.port }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.kibana.service.type "NodePort") .Values.kibana.service.nodePort }}
      nodePort: {{ .Values.kibana.service.nodePort }}
      {{- end }}
  selector:
    app: kibana
    release: {{ .Release.Name }}
