spring:
  application:
    name: cash
  config:
    import: "optional:consul:"

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}

      config:
        enabled: true
        prefix: config
        default-context: application
        format: YAML

      discovery:
        enabled: true
        register: true
        instance-id: "${spring.application.name}:${server.port}:${random.value}"
        health-check-path: /actuator/health
        health-check-interval: 10s

server:
  port: ${SERVER_PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info