apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 9600
      targetPort: 9600
      protocol: TCP
      name: api
  selector:
    app: logstash
    release: {{ .Release.Name }}
