apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cash-secret
  labels:
    app: cash
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CASH_SERVICE_CLIENT_SECRET: {{ .Values.security.oauth2.clientSecret | b64enc | quote }}
