apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-init
  labels:
    app: postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  init-keycloak-db.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE USER {{ .Values.databases.keycloak.user }} WITH PASSWORD '{{ .Values.databases.keycloak.password }}';
      CREATE DATABASE {{ .Values.databases.keycloak.name }} OWNER {{ .Values.databases.keycloak.user }};
      GRANT ALL PRIVILEGES ON DATABASE {{ .Values.databases.keycloak.name }} TO {{ .Values.databases.keycloak.user }};
    EOSQL
