apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-credentials
  labels:
    app: postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.databases.bank.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.databases.bank.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.databases.bank.name | b64enc | quote }}
  KEYCLOAK_DB_USER: {{ .Values.databases.keycloak.user | b64enc | quote }}
  KEYCLOAK_DB_PASSWORD: {{ .Values.databases.keycloak.password | b64enc | quote }}
  KEYCLOAK_DB_NAME: {{ .Values.databases.keycloak.name | b64enc | quote }}
