apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: postgresql
  selector:
    app: postgres
    release: {{ .Release.Name }}
