apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-notifications-config
  labels:
    app: notifications
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  SERVER_PORT: {{ .Values.service.port | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.global.keycloak.issuerUri | quote }}
  BANK_SECURITY_ENABLED: {{ .Values.security.enabled | quote }}
