apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-notifications-config
  labels:
    app: notifications
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  SERVER_PORT: {{ .Values.service.containerPort | quote }}
  BANK_SECURITY_ENABLED: {{ .Values.security.enabled | quote }}
  SPRING_CONFIG_ADDITIONAL_LOCATION: /app/config/
  application.yml: |
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ .Values.global.keycloak.issuerUri }}
              jwk-set-uri: {{ .Values.global.keycloak.jwkSetUri }}
