apiVersion: v1
kind: Service
metadata:
  name: notifications
  labels:
    app: notifications
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: management
  selector:
    app: notifications
    release: {{ .Release.Name }}
