spring:
  application:
    name: notifications
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notifications-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ru.yandex.practicum.bank.common.dto"
        spring.json.use.type.headers: false
        spring.json.value.default.type: ru.yandex.practicum.bank.common.dto.NotificationEvent
    listener:
      ack-mode: manual_immediate

bank:
  kafka:
    topic:
      notifications: bank.notifications
